### ISSUE TITLE
Planejar avaliações de 2018

### ISSUE THREAD

**Issue by philsf** [philsf/Bioestatistica#138]
Esta issue passa a ser o monitoramento da inclusão deste esclarecimento em cada uma das aulas acima. Quando todas forem concluídas, esta issue poderá ser manualmente fechada.

- [x] Intro ( #82 )
-  ~~IC 2prop~~ ( #134 )
- [x] Variabilidade ( #121 )
- [x] IC média ( #117 )
- [x] IC diferença 2 médias ( #135 )
- [x] RR e OR ( #118 )
- [x] Significância (#125 )
- [x] Teste t ( #126 )
- [x] Teste Qui2/Fisher ( #127 )
- [x] Correlação ( #128 )
- [x] Regressão Linear ( #129 )
- [x] Regressão Logística ( #132 )
- [x] ANOVA ( #130 )
- [x] Métodos não paramétricos ( #131 )

Após a conclusão de todas as issues, fechar manualmente também:

- o projeto Tarefas GC
- a issue philsf-biostat/org/issues/9

**Comment by philsf** [comment]
Closes philsf-biostat/org/issues/9
