### ISSUE TITLE
Esclarecer variável dependente e independente em cada teste

### ISSUE THREAD

**Issue by philsf** [philsf/Bioestatistica#77]
Os alunos ainda têm dificuldade de identificar Qual é a variável dependente é a variável independente no teste t e em outros testes.

Considerar tornar explícito em cada aula que tenha testes Quais são as variáveis do teste.

- [x] IC da diferença de 2 médias (cap 5, 7)
- [x] IC da diferença/razão de 2 props (cap 8, 9)
- [x] Significância (Cap 10, 11)
- [x] Teste t (cap 23, 25) #163 
- [x] Teste prop (cap 26, 27) #164 
- [x] Correlação (Cap 17) #165 
- [ ] Regressão (cap 18, 19)
- [x] Comparações múltiplas + ANOVA (Cap 13, 30) #166 
- [x] Métodos não paramétricos (Cap 37, 38) #167 

Esta issue passa a ser o monitoramento da inclusão deste esclarecimento em cada uma das aulas acima. Quando todas forem concluídas, esta issue poderá ser manualmente fechada.

**Comment by philsf** [comment]
A aula de Regressão linear será replanejada, então esta issue já contém novidades suficientes para o fechamneto.
